[[inputs.mqtt_consumer]]
  ## HiveMQ Cloud URL (Use port 8883 for SSL)
  servers = ["ssl://YOUR_HIVEMQ_ID.s1.eu.hivemq.cloud:8883"]
  topics = ["sensors/esp32/#"]
  username = "your_hivemq_username"
  password = "your_hivemq_password"
  data_format = "json"

[[outputs.influxdb_v2]]
  ## "influxdb" here refers to the container name in Docker
  urls = ["http://influxdb:8086"]
  token = "YOUR_INFLUX_TOKEN"
  organization = "MyHome"
  bucket = "ESP32_Data"