INFLUXDB_URL = "http://localhost:8086"
INFLUXDB_TOKEN = "YOUR_ACTUAL_INFLUX_API_TOKEN_HERE"
INFLUXDB_ORG = "my_organization"
INFLUXDB_BUCKET = "water_treatment"
UDP_IP = "0.0.0.0"
UDP_PORT = 5005
UDP_BUFFER_SIZE = 1024
